### ISSUE TITLE
TF version 2

### ISSUE THREAD

**Issue by seunboy1** [leggedrobotics/tensorflow-cpp#3]
Hi thank you,

Please how do i install tf 2.x

**Comment by vastsoun** [comment]
Hi,

This project currently does not support `tensorflow>=2.0`. If you want to try and generating this yourself I recommend starting from our build recipe for [`1.15.x`](https://github.com/leggedrobotics/tensorflow-cpp/tree/master/tensorflow/bin/r1.15). We do plan to add support for `tensorflow==2.2` in the near future but I cannot give you a concrete date for this.

**Comment by seunboy1** [comment]
Thank you
