### ISSUE TITLE
Could NOT find TensorFlow (missing: TensorFlow_LIBRARIES) Call Stack (most recent call first):

### ISSUE THREAD

**Issue by kashifzr** [leggedrobotics/tensorflow-cpp#4]
<pre><font color="#8AE234"><b>abc@abc</b></font>:<font color="#729FCF"><b>~/raisim_ws_1/tensorflow-cpp/examples</b></font>$ cmake .
-- The CXX compiler identification is GNU 7.5.0
-- Check for working CXX compiler: /usr/lib/ccache/c++
-- Check for working CXX compiler: /usr/lib/ccache/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at /usr/local/share/cmake-3.14/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find TensorFlow (missing: TensorFlow_LIBRARIES)
Call Stack (most recent call first):
  /usr/local/share/cmake-3.14/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /home/abc/.local/share/TensorFlow/cmake/tensorflow-config.cmake:56 (find_package_handle_standard_args)
  CMakeLists.txt:23 (find_package)

-- Configuring incomplete, errors occurred!
See also &quot;/home/abc/raisim_ws_1/tensorflow-cpp/examples/CMakeFiles/CMakeOutput.log&quot;.
</pre>

Can some guide how to install the tensorflow-cpp, I am using the instruction on the README the following tensorflow Libraries are missing while cmake

**Comment by vastsoun** [comment]
Hi Kashif,

Are you trying to build the examples or install tensorflow-cpp?

1. First you have to decide where you want to install it. I recommend `~/.local` since this won't polute the global filesystem.
2. Next we need to install tensorflow-cpp.
```
cd tensorflow-cpp/tensorflow
mkdir build && cd build
cmake -DCMAKE_INSTALL_PREFIX=~/.local -DCMAKE_BUILD_TYPE=Release ..
make install -j
```
3. Then you can build and run the example:
```
cd tensorflow-cpp/examples
mkdir build && cd build
cmake -DCMAKE_PREFIX_PATH=~/.local -DCMAKE_BUILD_TYPE=Release ..
make tf_example_trainer -j
./src/tensorflow-cpp/examples/tf_example_trainer
```

Some comments:
1. I do not recommend to run cmake in-place in the repo. Create `build/` dirs to isolate all the build artifcts so you can just delete that directory if you wan't to clean it out of your system.
2. `CMAKE_INSTALL_PREFIX` tells CMake where to install stuff after it's built.
3. `CMAKE_PREFIX_PATH` tells CMake where to look for CMake packages that we have installed manually such as the `tensorflow` package in this repo.
4. Don't forget to specify whether you want to use CPU or GPU version using the `TF_USE_GPU` option, for example:
```
cd tensorflow-cpp/tensorflow
mkdir build && cd build
cmake -DCMAKE_INSTALL_PREFIX=~/.local -DCMAKE_BUILD_TYPE=Release -DTF_USE_GPU=On ..
make install -j
```
5. The `tensorflow-cpp/tensorflow/CMakeLists.txt`, when run for the first time, will try and download the pre-built binaries into the `tensorflow-cpp/tensorflow/lib` directory, e.g. `1.15.2-gpu.zip`. Building it the first time, you will see a bunch of print-outs from the download process. Make sure **NOT** to interrupt it. To be sure, I would delete everything in the `tensorflow-cpp/tensorflow/lib` directory and re-run the installation process of `tensorflow-cpp/tensorflow`.

**Comment by kashifzr** [comment]
HI Vastsoun Thanks for Details Description
I fully understand the points you share about the installation of tensorflow,  I am using these command frequently but for tensorflow-cpp I try couple of times the problem is still same let me share the outcome of first three points 

<pre><font color="#8AE234"><b>abc@abc</b></font>:<font color="#729FCF"><b>~/raisim_ws_1</b></font>$ git clone git@github.com:leggedrobotics/tensorflow-cpp.git
Cloning into &apos;tensorflow-cpp&apos;...
remote: Enumerating objects: 102, done.
remote: Counting objects: 100% (102/102), done.
remote: Compressing objects: 100% (61/61), done.
remote: Total 2039 (delta 49), reused 89 (delta 39), pack-reused 1937
Receiving objects: 100% (2039/2039), 2.73 MiB | 2.19 MiB/s, done.
Resolving deltas: 100% (435/435), done.
<font color="#8AE234"><b>abc@abc</b></font>:<font color="#729FCF"><b>~/raisim_ws_1</b></font>$ ls
</pre>

abc@abc:~/raisim_ws_1/tensorflow-cpp/eigen$ ls
eigen3  install.sh  LICENSE  package.xml.in
abc@abc:~/raisim_ws_1/tensorflow-cpp/eigen$ 


<pre><font color="#8AE234"><b>abc@abc</b></font>:<font color="#729FCF"><b>~/raisim_ws_1/tensorflow-cpp</b></font>$ cd tensorflow
<font color="#8AE234"><b>abc@abc</b></font>:<font color="#729FCF"><b>~/raisim_ws_1/tensorflow-cpp/tensorflow</b></font>$ ls
<font color="#729FCF"><b>bin</b></font>  <font color="#729FCF"><b>cmake</b></font>  CMakeLists.txt  <font color="#729FCF"><b>lib</b></font>  package.xml
<font color="#8AE234"><b>abc@abc</b></font>:<font color="#729FCF"><b>~/raisim_ws_1/tensorflow-cpp/tensorflow</b></font>$ mkdir build
<font color="#8AE234"><b>abc@abc</b></font>:<font color="#729FCF"><b>~/raisim_ws_1/tensorflow-cpp/tensorflow</b></font>$ cd build
<font color="#8AE234"><b>abc@abc</b></font>:<font color="#729FCF"><b>~/raisim_ws_1/tensorflow-cpp/tensorflow/build</b></font>$ cmake -DCMAKE_INSTALL_PREFIX=~/.local -DCMAKE_BUILD_TYPE=Release ..
-- The CXX compiler identification is GNU 7.5.0
-- Check for working CXX compiler: /usr/lib/ccache/c++
-- Check for working CXX compiler: /usr/lib/ccache/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- tensorflow-cpp: Downloading binaries from &apos;https://github.com/leggedrobotics/tensorflow-cpp/releases/download/v0.2.0/1.15.2-cpu.zip&apos; as &apos;/home/abc/raisim_ws_1/tensorflow-cpp/tensorflow/lib/1.15.2-cpu.zip&apos;. Please wait until completed ...
-- tensorflow-cpp: Completed download of &apos;https://github.com/leggedrobotics/tensorflow-cpp/releases/download/v0.2.0/1.15.2-cpu.zip&apos;.
-- tensorflow-cpp: Extracting &apos;https://github.com/leggedrobotics/tensorflow-cpp/releases/download/v0.2.0/1.15.2-cpu.zip&apos; ...
-- tensorflow-cpp: Completed extraction of &apos;https://github.com/leggedrobotics/tensorflow-cpp/releases/download/v0.2.0/1.15.2-cpu.zip&apos;.
-- Configuring done
-- Generating done
-- Build files have been written to: /home/abc/raisim_ws_1/tensorflow-cpp/tensorflow/build
</pre>



<pre><font color="#8AE234"><b>abc@abc</b></font>:<font color="#729FCF"><b>~/raisim_ws_1/tensorflow-cpp/tensorflow/build</b></font>$ make install -j
<font color="#06989A">Install the project...</font>
-- Install configuration: &quot;Release&quot;
-- Installing: /home/abc/.local/share/TensorFlow/cmake/TensorFlow-targets.cmake
-- Installing: /home/abc/.local/share/TensorFlow/cmake/tensorflow-config.cmake
-- Installing: /home/abc/.local/share/TensorFlow/cmake/tensorflow-config-version.cmake
-- Up-to-date: /home/abc/.local/include/tensorflow
<font color="#8AE234"><b>abc@abc</b></font>:<font color="#729FCF"><b>~/raisim_ws_1/tensorflow-cpp/tensorflow/build</b></font>$ 
</pre>



<pre><font color="#8AE234"><b>abc@abc</b></font>:<font color="#729FCF"><b>~/raisim_ws_1/tensorflow-cpp/examples</b></font>$ mkdir build
<font color="#8AE234"><b>abc@abc</b></font>:<font color="#729FCF"><b>~/raisim_ws_1/tensorflow-cpp/examples</b></font>$ cd build
<font color="#8AE234"><b>abc@abc</b></font>:<font color="#729FCF"><b>~/raisim_ws_1/tensorflow-cpp/examples/build</b></font>$ ls
<font color="#8AE234"><b>abc@abc</b></font>:<font color="#729FCF"><b>~/raisim_ws_1/tensorflow-cpp/examples/build</b></font>$ cmake -DCMAKE_PREFIX_PATH=~/.local -DCMAKE_BUILD_TYPE=Release ..
-- The CXX compiler identification is GNU 7.5.0
-- Check for working CXX compiler: /usr/lib/ccache/c++
-- Check for working CXX compiler: /usr/lib/ccache/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at /usr/local/share/cmake-3.14/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find TensorFlow (missing: TensorFlow_LIBRARIES)
Call Stack (most recent call first):
  /usr/local/share/cmake-3.14/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /home/abc/.local/share/TensorFlow/cmake/tensorflow-config.cmake:56 (find_package_handle_standard_args)
  CMakeLists.txt:23 (find_package)


-- Configuring incomplete, errors occurred!
See also &quot;/home/abc/raisim_ws_1/tensorflow-cpp/examples/build/CMakeFiles/CMakeOutput.log&quot;.
</pre>

I hope my command executions will give some idea why the problem is still the same

**Comment by vastsoun** [comment]
This part looks wrong:
```
abc@abc:~/raisim_ws_1/tensorflow-cpp/tensorflow/build$ make install -j
Install the project...
-- Install configuration: "Release"
-- Installing: /home/abc/.local/share/TensorFlow/cmake/TensorFlow-targets.cmake
-- Installing: /home/abc/.local/share/TensorFlow/cmake/tensorflow-config.cmake
-- Installing: /home/abc/.local/share/TensorFlow/cmake/tensorflow-config-version.cmake
-- Up-to-date: /home/abc/.local/include/tensorflow
abc@abc:~/raisim_ws_1/tensorflow-cpp/tensorflow/build$ 
```
It shows us that it is **NOT** installing the prebuilt `*.so` files or any headers. It should look somethign like:
```
vassilios@tsounix:~/git/tensorflow/tensorflow-cpp/tensorflow/build$ cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=~/.tensorflow ..
...
...
vassilios@tsounix:~/git/tensorflow/tensorflow-cpp/tensorflow/build$ make install -j
Install the project...
-- Install configuration: "Release"
-- Installing: /home/vassilios/.tensorflow/share/TensorFlow/cmake/TensorFlow-targets.cmake
-- Installing: /home/vassilios/.tensorflow/share/TensorFlow/cmake/tensorflow-config.cmake
-- Installing: /home/vassilios/.tensorflow/share/TensorFlow/cmake/tensorflow-config-version.cmake
-- Installing: /home/vassilios/.tensorflow/include/tensorflow/Eigen
...
<ALLOT OF HEADERS>
...
-- Installing: /home/vassilios/.tensorflow/lib/libtensorflow_cc.so
-- Installing: /home/vassilios/.tensorflow/lib/libtensorflow_cc.so.1
-- Installing: /home/vassilios/.tensorflow/lib/libtensorflow_cc.so.1.15.2
-- Installing: /home/vassilios/.tensorflow/lib/libtensorflow_framework.so.1
-- Installing: /home/vassilios/.tensorflow/lib/libtensorflow_framework.so.1.15.2
```

As I said in the previous post, I think the download and extraction process probably failed. If you `ls` into `tensorflow-cpp/tensorflow/lib/`, what do you see?

Delete all the contents of `tensorflow-cpp/tensorflow/lib/` and re-run.

**Comment by kashifzr** [comment]
Now I know Why I am getting this issue, I am trying to figure out this but at the same time I did ls in workspace/tensorflow-cpp/tensorflow/lib and the output of ls is also shared 


<pre><font color="#8AE234"><b>abc@abc</b></font>:<font color="#729FCF"><b>~/raisim_ws_1/tensorflow-cpp/tensorflow</b></font>$ cd lib
<font color="#8AE234"><b>abc@abc</b></font>:<font color="#729FCF"><b>~/raisim_ws_1/tensorflow-cpp/tensorflow/lib</b></font>$ ls
<font color="#EF2929"><b>1.15.2-cpu.zip</b></font>
<font color="#8AE234"><b>abc@abc</b></font>:<font color="#729FCF"><b>~/raisim_ws_1/tensorflow-cpp/tensorflow/lib</b></font>$ 
</pre>


When I downloaded tensorflow-cpp and run the ~/.install.sh --run-cmake command to install eigen for tensorflow then installation works normally. however last couple of time its make issues only when i run other commands specific to build and install tensorflow


Thanks Vassilios Tsounis for Guidance for this issue. I will try to resolve this mystery and issue with my little bit knowledge

**Comment by ZQX323** [comment]
I have the same problem. Seems like you did not download the file properly. You can direct download from the link:

https://github.com/leggedrobotics/tensorflow-cpp/releases/download/v0.2.0/1.15.2-cpu.zip 

and copy the file to tensorflow-cpp/tensorflow/lib
Then run cmake 

It works for me. It seems like there is something wrong in CMakeList.txt. But I have not found it.

**Comment by kashifzr** [comment]
Thanks ZQX323 for sharing the trick that I must try before, your idea save my time. Thanks Vassilios for valuable Guidance to solve issues related to tensorflow-cpp installation
