### ISSUE TITLE
Could NOT find TensorFlow (missing: TensorFlow_LIBRARIES)

### ISSUE THREAD

**Issue by likq2018** [leggedrobotics/tensorflow-cpp#5]
Hello!
Thank you for having provided the project.
The problem is that Could NOT find TensorFlow (missing: TensorFlow_LIBRARIES) When I look for packages through cmake.
Then I  find this website  https://gitmemory.com/issue/leggedrobotics/tensorflow-cpp/4/719531446. 
Here is my installation information.
likq@ubuntu:~/Software/raisim_workspace/MySimGym/tensorflow-cpp/tensorflow/build$ make install -j
Install the project...
-- Install configuration: "Release"
-- Installing: /home/likq/.tensorflow/share/TensorFlow/cmake/TensorFlow-targets.cmake
-- Installing: /home/likq/.tensorflow/share/TensorFlow/cmake/tensorflow-config.cmake
-- Installing: /home/likq/.tensorflow/share/TensorFlow/cmake/tensorflow-config-version.cmake
-- Installing: /home/likq/.tensorflow/include/tensorflow
likq@ubuntu:~/Software/raisim_workspace/MySimGym/tensorflow-cpp/tensorflow/build$ 

Then I delete all the contents of tensorflow-cpp/tensorflow/lib/ and re-run. But the problem remains unsolved.
So, can you some guidance how to install the tensorflow-cpp. 
Thank you very much!

**Comment by vastsoun** [comment]
You have to be carefull when you run the cmake command the first time:
```
cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=<YOUR-PREFIX>
```

It should show you some output that it is downloading the archive with the pre-built lib such as:
![image](https://user-images.githubusercontent.com/2759676/101971415-78a3d900-3c31-11eb-89b0-6e3311bd329e.png)

And a `1.15.2-gpu.zip` file and `1.15.2-gpu` directory should appear. If these are not present in your `tensorflow-cpp/tensorflow/lib` directory then something went wrong during the cmake build step. Also please read the `tensorflow-cpp/tensorflow/CMakeLists.txt' to see the package condiguration options and how to use them.

**Comment by likq2018** [comment]
Thank you for your reply！
The picture you provided cannot be displayed.
Here is my new installation information.
likq@ubuntu:~/Documents/tensorflow-cpp/tensorflow$ mkdir build && cd build
likq@ubuntu:~/Documents/tensorflow-cpp/tensorflow/build$ cmake -DCMAKE_INSTALL_PREFIX=~/.local -DCMAKE_BUILD_TYPE=Release ..
-- The CXX compiler identification is GNU 8.4.0
-- Check for working CXX compiler: /usr/bin/g++-8
-- Check for working CXX compiler: /usr/bin/g++-8 -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- tensorflow-cpp: Downloading binaries from 'https://github.com/leggedrobotics/tensorflow-cpp/releases/download/v0.2.0/1.15.2-cpu.zip' as '/home/likq/Documents/tensorflow-cpp/tensorflow/lib/1.15.2-cpu.zip'. Please wait until completed ...
-- tensorflow-cpp: Completed download of 'https://github.com/leggedrobotics/tensorflow-cpp/releases/download/v0.2.0/1.15.2-cpu.zip'.
-- tensorflow-cpp: Extracting 'https://github.com/leggedrobotics/tensorflow-cpp/releases/download/v0.2.0/1.15.2-cpu.zip' ...
-- tensorflow-cpp: Completed extraction of 'https://github.com/leggedrobotics/tensorflow-cpp/releases/download/v0.2.0/1.15.2-cpu.zip'.
-- Configuring done
-- Generating done
-- Build files have been written to: /home/likq/Documents/tensorflow-cpp/tensorflow/build
likq@ubuntu:~/Documents/tensorflow-cpp/tensorflow/build$ make install -j
Install the project...
-- Install configuration: "Release"
-- Installing: /home/likq/.local/share/TensorFlow/cmake/TensorFlow-targets.cmake
-- Installing: /home/likq/.local/share/TensorFlow/cmake/tensorflow-config.cmake
-- Installing: /home/likq/.local/share/TensorFlow/cmake/tensorflow-config-version.cmake
-- Up-to-date: /home/likq/.local/include/tensorflow
likq@ubuntu:~/Documents/tensorflow-cpp/tensorflow/build$ 

Then I read the `tensorflow-cpp/tensorflow/CMakeLists.txt' and find that the URL 

"https://github.com/leggedrobotics/tensorflow-cpp/releases/download"

does not exist.

So what solution is there at this time.
Thank you very much!

**Comment by vastsoun** [comment]
The link you posted is not complete.
Here is the full link `https://github.com/leggedrobotics/tensorflow-cpp/releases/download/v0.2.0/1.15.2-gpu.zip`.
You can also just grab the ZIP files directly from here:
`https://github.com/leggedrobotics/tensorflow-cpp/releases`

Also, keep in mind since you seem to be installing it in `$~/.local`, you also need to add or specify it in the `CMAKE_PREFIX_PATH` of wherever you are running cmake so `find_package()` can find `TensorFlow`. For example in your project or workspace:
```
cmake .. -DCMAKE_PREFIX_PATH=~/.local
```
or in your CMakeLists.txt
```
list(APPEND CMAKE_PREFIX_PATH "~/.local")
```

**Comment by likq2018** [comment]
Thank you very much! The problem has been solved.
